---
- name: Create .pyenv/bin
  file: path=/Users/{{ ansible_user_id }}/.pyenv/bin state=directory mode=0755

- name: Install pip
  shell: |
    easy_install pip

- name: Upgrade pip
  shell: |
    pip install --upgrade pip

- name: Install python packages via pip
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    executable: pip
  with_items:
    - "{{ pip_packages }}"
